#!/usr/bin/env python3
"""
Generate a C header containing raw string literals with embedded XML
for files from https://autotest.ardupilot.org/LogMessages/ (i.e. Plane.xml and Copter.xml)
If they are missing, emit empty strings so the code compiles but no embedded content is used.

Usage:
  generate_LogMessageDescriptions_header.py <input_dir> <output_header>

The script reads any xml files in <input_dir> and merges them into a single header file.
Any updates to the XML files requires rebuilding the project to embed the new content.
"""
import sys
import os

def read_file_safe(path):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception:
        return ''

def make_raw_string(name, content):
    # Use a delimiter unlikely to appear in XML
    delim = 'XML_DELIM'
    return 'static const char ' + name + '[] = R"' + delim + '(' + content + ')' + delim + '";\n\n'

def main():
    if len(sys.argv) < 3:
        print('Usage: generate_LogMessageDescriptions_header.py <input_dir> <output_header>')
        return 2
    input_dir = sys.argv[1]
    out_path = sys.argv[2]

    contents = []
    contents.append('/* Auto-generated by generate_LogMessageDescriptions_header.py */')
    contents.append('#pragma once')
    contents.append('\n')

    # Read any XML files in the input directory and merge them into one embedded variable.
    merged = []
    if os.path.isdir(input_dir):
        for entry in sorted(os.listdir(input_dir)):
            # accept files with .xml extension (case-insensitive) or any file
            if not os.path.isfile(os.path.join(input_dir, entry)):
                continue
            _, ext = os.path.splitext(entry)
            if ext.lower() != '.xml':
                # skip non-XML files
                continue
            fpath = os.path.join(input_dir, entry)
            xml = read_file_safe(fpath)
            if not xml:
                continue
            # strip BOM if present
            if xml.startswith('\ufeff'):
                xml = xml.lstrip('\ufeff')
            merged.append(xml)

    # Strip XML prologs and wrap merged content in a single root so the parser
    # can consume multiple files as one well-formed XML document.
    processed = []
    for xml in merged:
        s = xml.lstrip()
        if s.startswith('<?xml'):
            idx = s.find('?>')
            if idx != -1:
                s = s[idx+2:]
        processed.append(s)

    merged_inner = '\n'.join(processed)
    if merged_inner:
        merged_content = '<loggermessagefilecollection>\n' + merged_inner + '\n</loggermessagefilecollection>'
    else:
        merged_content = ''

    contents.append(make_raw_string('kEmbeddedLogMessagesXml', merged_content))

    # Write header directory (ensure parent exists)
    os.makedirs(os.path.dirname(out_path) or '.', exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as out:
        out.write('\n'.join(contents))

    return 0

if __name__ == '__main__':
    sys.exit(main())
